widgetTheme=widget-themes/original
primaryColor=#36a9e1
secondaryColor=#86C953
labelColor=#ffffff
hideWhenOffline=
contactMail=seu@email.com
loadingLabel=Carregando...
loginError=Login error
chatHeader=Atendimento online
startInfo=Por favor preencha o seguinte formulário para iniciar o bate-papo
widgetWidth=370
widgetHeight=411
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=Iniciar
backLabel=Voltar
initMessageBody=Olá, como posso ajudar?
initMessageAuthor=Operador
chatInputLabel=Digite sua pergunta
timeDaysAgo=dia(s) atrás
timeHoursAgo=houras(s) atrás
timeMinutesAgo=minutos(s) atrás
timeSecondsAgo=segundos(s) atrás
offlineMessage=Operador ficou offline
toggleSoundLabel=Efeitos sonoros
toggleScrollLabel=Auto-scroll
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Auto-show
toggleFullscreenLabel=Exibição em tela cheia
endChatLabel=Encerrar chat
endChatConfirmQuestion=Você tem certeza?
endChatConfirm=Sim
endChatCancel=Cancelar
contactHeader=Fale conosco
contactInfo=Todos os operadores estão offline. Utilize o formulário abaixo para nos enviar um e-mail com a sua pergunta.
contactNameLabel=Seu nome
contactMailLabel=Seu Email
contactQuestionLabel=Sua pergunta
contactSendLabel=Enviar
contactSuccessHeader=Mensagem enviada
contactSuccessMessage=Sua pergunta foi enviada. Obrigado!
contactErrorHeader=Erro
contactErrorMessage=Houve um erro ao enviar a sua pergunta
headerHeight=55
installed=
autoShowWidgetAfter=10
autoShowWidget=true
askForMail=true